name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build push elasticsearch
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch
          file: ./elasticsearch/Dockerfile
          push: true
          tags: ttbb/elasticsearch:stand-alone
          platforms: linux/amd64,linux/arm64
      - name: build push kibana
        uses: docker/build-push-action@v2
        with:
          context: ./kibana
          file: ./kibana/Dockerfile
          push: true
          tags: ttbb/kibana:stand-alone
          platforms: linux/amd64,linux/arm64
      - name: build push elasticsearch-kibana
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch-kibana
          file: ./elasticsearch-kibana/Dockerfile
          push: true
          tags: ttbb/integrate:elasticsearch-kibana
          platforms: linux/amd64,linux/arm64
