name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch
          file: ./elasticsearch/Dockerfile
          push: true
          tags: ttbb/elasticsearch:stand-alone
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./kibana
          file: ./kibana/Dockerfile
          push: true
          tags: ttbb/kibana:stand-alone
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch-kibana
          file: ./elasticsearch-kibana/Dockerfile
          push: true
          tags: ttbb/integrate:elasticsearch-kibana